### ISSUE TITLE
What is project-viewer-credentials.json?

### ISSUE THREAD

**Issue by SamuelMarks** [doitintl/SafeScrub#4]
I tried this solution:
```sh
-k ~/'.config/gcloud/legacy_credentials/myemail@gmail.com/adc.json'
```

But it said:
> ERROR: (gcloud.auth.activate-service-account) The .json key file is not in a valid format.

The contents are:
```json
{
  "account": "",
  "client_id": "someidhere.apps.googleusercontent.com",
  "client_secret": "somesmallsecret",
  "refresh_token": "somebigtoken",
  "type": "authorized_user",
  "universe_domain": "googleapis.com"
}
```

**Comment by JoshuaFox** [comment]
Samuel, 

Glad to know that you are using SafeScrub. It is a bit old, but I  will try to help you as feasible. You might also take a look at [Cloud Blaster](https://github.com/doitintl/CloudBlaster ), which is newer and  more flexible (since it is in Kotlin rather than shell), but SafeScrub is different and may have value to you. 

If I understand correctly, you are using the `-k` switch on `generate-deletion-script.sh`. 

You seem to have used some sort of default existing credentials. 
I created a[ service account](https://console.cloud.google.com/iam-admin/serviceaccounts/) -> add Viewer permissions ->Manage Keys-> Create Key-> Download JSON

I downloaded the file to the same directory as SafeScrub, and gave it the name `project-viewer-credentials.json`.

Doing it this way is a way of getting reassurance  that running the  `generate-deletion-script.sh` script is itself fully safe

Here is the JSON, redacted.
```
{
  "type": "service_account",
  "project_id": "myproject",
  "private_key_id": "ccbabababababababababababaababab111111eeeee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMII.....JVQ==\n-----END PRIVATE KEY-----\n",
  "client_email": "viewersa@myproject.iam.gserviceaccount.com",
  "client_id": "9990000222221111",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/viewersa%40myproject.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

```

Then I ran the `generate-deletion-script.sh`

For further interaction, feel free to email me at `<my first name> @ doit.com`.

**Comment by SamuelMarks** [comment]
Perfect thanks. Just joined this project and there were over 30 resources your script found that I can just remove! - Removed maybe a hundred manually through the web interface earlier…
